### ISSUE TITLE
[Feature request] Add FEM read support for GBARM sesam beam elements

### ISSUE THREAD

**Issue by oleandor** [Krande/adapy#4]
Genie beam with Bar section is converted to IfcCircleProfileDef

```
from ada import Assembly
path = r'c:\test'
fem_file = path + '\T10.FEM'
a = Assembly('myAssembly')
a.read_fem(fem_file, fem_name='myModel')
p = a.parts['myModel']
p.fem.convert_ecc_to_mpc()
a.create_objects_from_fem()
a.to_ifc(path + '\T10')
```

**Comment by Krande** [comment]
Hello! Thanks for submitting this issue:) Do you have a small example file you can share with this Bar section? If it is not shareable you could send me the example file privately?

**Comment by Krande** [comment]
Aha, now I see. The GBARM (bar section) is not yet supported by the sesam reader. Currently it uses only the general section representation (which is as far as I am aware also imported for all beam members in sesam). 

For now I can add a logging error to make the user aware whenever "artificial" members are converted to physical beam members (which might not be ideal) in the `create_objects_from_fem()` method. 

I can add this to the sesam reader after easter!

**Comment by Krande** [comment]
Added support for reading GBARM elements with commit https://github.com/Krande/adapy/commit/18481d65739a1423a3423beaffcecf0f4f975c18
